steps:
  # 1. Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/crux-ai-backend:$BUILD_ID",
        "-f",
        "backend/Dockerfile",
        "backend",
      ]

  # 2. Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/crux-ai-backend:$BUILD_ID"]

  # 3. Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "crux-ai-backend",
        "--image",
        "gcr.io/$PROJECT_ID/crux-ai-backend:$BUILD_ID",
        "--region",
        "us-east4",
        "--platform",
        "managed",
        "--set-secrets",
        "GEMINI_API_KEY=GEMINI_API_KEY:latest,APIFY_API_TOKEN=APIFY_API_TOKEN:latest",
        "--quiet",
      ]

  # 4. Allow unauthenticated access to the service
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "services",
        "add-iam-policy-binding",
        "crux-ai-backend",
        "--region=us-east4",
        "--member=allUsers",
        "--role=roles/run.invoker",
      ]

# This section is for substituting the secret at build time
# You need to have the GEMINI_API_KEY secret in Secret Manager
# And grant the Cloud Build service account access to it
# availableSubstitutions:
#   _GEMINI_API_KEY: ''
# secrets:
# - kmsKeyName: projects/YOUR_GCP_PROJECT_ID/locations/YOUR_GCP_REGION/keyRings/YOUR_KEYRING/cryptoKeys/YOUR_KEY
#   secretEnv:
#     GEMINI_API_KEY: 'YOUR_SECRET_NAME'
images:
  - "gcr.io/$PROJECT_ID/crux-ai-backend:$BUILD_ID"
